# Generated by Django 5.2.8 on 2025-11-20 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_anggota', models.CharField(max_length=10, unique=True, verbose_name='Nomor Anggota')),
                ('nama_lengkap', models.CharField(max_length=100, verbose_name='Nama Lengkap')),
                ('email', models.EmailField(max_length=254, verbose_name='Alamat Email')),
                ('no_telepon', models.CharField(blank=True, max_length=15, verbose_name='Nomor Telepon')),
                ('alamat', models.TextField(verbose_name='Alamat')),
                ('tanggal_daftar', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('judul', models.CharField(max_length=200, verbose_name='Judul Buku')),
                ('penulis', models.CharField(max_length=100, verbose_name='Penulis')),
                ('kategori', models.CharField(choices=[('FIKSI', 'Fiksi'), ('NONFIKSI', 'Non-Fiksi'), ('TEKNOLOGI', 'Teknologi'), ('SEJARAH', 'Sejarah'), ('SASTRA', 'Sastra')], default='FIKSI', max_length=10)),
                ('tahun_terbit', models.IntegerField(verbose_name='Tahun Terbit')),
                ('penerbit', models.CharField(max_length=100, verbose_name='Penerbit')),
                ('stok', models.IntegerField(default=1, verbose_name='Stok Tersedia')),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pinjam', models.DateField(auto_now_add=True, verbose_name='Tanggal Pinjam')),
                ('tanggal_kembali', models.DateField(verbose_name='Tanggal Kembali')),
                ('tanggal_dikembalikan', models.DateField(blank=True, null=True, verbose_name='Tanggal Dikembalikan')),
                ('status', models.CharField(choices=[('DIPINJAM', 'Dipinjam'), ('DIKEMBALIKAN', 'Dikembalikan'), ('TERLAMBAT', 'Terlambat')], default='DIPINJAM', max_length=12)),
                ('denda', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Denda')),
                ('anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peminjaman', to='perpustakaan.anggota')),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peminjaman', to='perpustakaan.buku')),
            ],
        ),
    ]
